import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#fbf8ff',
        'surface-dim': '#dad9e5',
        'surface-bright': '#fbf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f2fe',
        'surface-container': '#eeecf9',
        'surface-container-high': '#e9e7f3',
        'surface-container-highest': '#e3e1ed',
        'on-surface': '#1a1b23',
        'on-surface-variant': '#454655',
        'inverse-surface': '#2f3039',
        'inverse-on-surface': '#f1effb',
        'outline': '#757686',
        'outline-variant': '#c5c5d7',
        'surface-tint': '#3b4cda',
        'primary': '#384ad8',
        'on-primary': '#ffffff',
        'primary-container': '#5465f2',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#bdc2ff',
        'secondary': '#5c5e63',
        'on-secondary': '#ffffff',
        'secondary-container': '#dedfe5',
        'on-secondary-container': '#606368',
        'tertiary': '#595b6d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#727387',
        'on-tertiary-container': '#fffbff',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dfe0ff',
        'primary-fixed-dim': '#bdc2ff',
        'on-primary-fixed': '#000a64',
        'on-primary-fixed-variant': '#1c2fc3',
        'secondary-fixed': '#e1e2e8',
        'secondary-fixed-dim': '#c5c6cc',
        'on-secondary-fixed': '#191c20',
        'on-secondary-fixed-variant': '#44474c',
        'tertiary-fixed': '#e1e1f7',
        'tertiary-fixed-dim': '#c4c5db',
        'on-tertiary-fixed': '#181a2a',
        'on-tertiary-fixed-variant': '#444557',
        'background': '#fbf8ff',
        'on-background': '#1a1b23',
        'surface-variant': '#e3e1ed',
        'mint-bg': '#DFF6E8',
        'mint-fg': '#33B679',
        'peach-bg': '#FDE9D9',
        'peach-fg': '#F5924B',
        'lavender-bg': '#EDE7FB',
        'lavender-fg': '#8C6BE0',
        'sky-bg': '#DDEFFB',
        'sky-fg': '#3E9FDB',
        'danger': '#EF5A5A',
        'warning': '#F5B940',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
      },
      backgroundImage: {
        'accent-gradient': 'linear-gradient(135deg, #6D7CFB 0%, #4E5BD6 55%, #3F3FA8 100%)',
      },
    },
  },
  plugins: [],
};
export default config;
